auto: true
name: "Sail Oyster Bay"
description: "Showcasing the sailing opportunities in Oyster Bay"

url: "[www.oysterbaysailing.com]"

cdn: http://cdn.oysterbaysailing.com
markdown: rdiscount
permalink: pretty
rdiscount extensions: [smart]